#!/bin/bash
# ports-by-ip - show destination ports permitted for a particular IP.
# 
# Read the output of policies-by-ip and output a list of ports that the 
# listed policies permit to the given IP address. 

IAM=$(basename $0)

# Global settings.

# Defaults, to be overridden by getopts below
JUNOS_DEFAULTS=junos-defaults-set.cfg
FILE=current

usage ()
{
	echo -e "usage:\tcat policy-list | ${IAM} [ -c config]"
	echo -e "\tpolices-by-ip ... | ${IAM} [config]"
	echo -e ""
	echo -e "Read the policies for each IP and output a list of ports permitted."
	echo -e ""
	echo -e "  -h\t: display this help"
	echo -e "  -c\t: configuration file to read from. (default is \"${FILE}\")"
	echo -e "  policy-list\t: output from policies-by-ip"
}

while getopts :hc: option; do
	case "${option}" in
		h)	usage
			exit 0
			;;
		c)	if [ -f "${OPTARG}" ]; then
				FILE="${OPTARG}"
			else
				exec >&2
				echo "${IAM}: file ${OPTARG} doesn't exist"
				exit 1
			fi
			;;
		:)	exec >&2
			echo "${IAM} option -{$OPTARG} requires and argument."
			usage
			exit 1
			;;
		\?)	exec >&2
			echo "${IAM}: invalid option -{$OPTARG}."
			usage
			exit 1
			;;
	esac
done
shift $((OPTIND - 1))

FILE="${FILE} ${JUNOS_DEFAULTS}"

while read ip policies; do
	echo -en "$ip\t"
	if [[ "${ip}" =~ ":" ]]; then 
		FROM_ZONE=$(echo ${ip} | awk -F '[:()]' '{print $2}')
		TO_ZONE=$(echo ${ip} | awk -F '[:()]' '{print $3}')
		ZONE_FILTER="from-zone ${FROM_ZONE} to-zone ${TO_ZONE}"
		ip=$(echo ${ip} | awk -F '[:()]' '{print $1}')
	fi
	# any
	app0=$( for p in $policies; do egrep "set security.*${ZONE_FILTER}.*policy $p match application any" ${FILE} \
		| egrep -o ' any$'
	done)
	# application
	app1=$(for p in $policies; do egrep "set security.*${ZONE_FILTER}.*policy $p match application" ${FILE} \
		| awk '{print "applications.*application " $12 ".*destination-port"}' \
		| egrep -f - ${FILE} | egrep -o '[0-9-]+$'
	done)
	# application-set
	app2=$(for p in $policies; do egrep "set security.*${ZONE_FILTER}.*policy $p match application" ${FILE} \
		| awk '{print "applications.*application-set " $12 }' \
		| egrep -f - ${FILE} | awk '{print "applications.*application " $6 ".*destination-port"}' \
		| egrep -f - ${FILE} | egrep -o '[0-9-]+$'
	done)
	for port in $app0 $app1 $app2; do
		if [[ "${port}" == "any" ]]; then
			for i in {1..65535}; do 
				echo $i;
			done
			break	# obviously all ports, so no need calc the rest.	
		elif [[ "${port}" =~ \- ]]; then
			A=$(echo $port | cut -d- -f1)
			B=$(echo $port | cut -d- -f2)
			for i in $(eval echo "{$A..$B}"); do
				echo $i;
			done
		else
			echo $port
		fi
	done | sort -n |uniq | tr '\n' ' '
	echo
done